### ISSUE TITLE
Spartan Gems Project

### ISSUE THREAD

**Issue by Gabo6480** [Foozey/The-Gems-Project#1]
Compatibility with Spartan Weaponry and Spartan Shields

**Comment by Foozey** [comment]
Probably not going to happen since both mods do basically the same thing.

**Comment by Gabo6480** [comment]
I don't see how would both mods be doing the same thing, your mod adds more upgrade tiers for currently existing tools, and spartans weaponry adds shield and weapon variants. For compatibility you can add your gem tiers over spartan's variants.

**Comment by Foozey** [comment]
Spartan Shields adds shield tiers, just like my mod does (eg. Iron Shield, Diamond Shield, etc.) Both mods add several of the same items.

Spartan Weaponry on the other hand, I could add compatibility for, but it's probably not super high on my priorities right now. Sorry, I may get to it one day though. Right now my focuses are updating the mod to 1.18, adding a config, and adding some new content.
